In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

data_dir = Path('data')
full_df = pd.concat(
    pd.read_parquet(parquet_file)
    for parquet_file in data_dir.glob('*.parquet*')
)
full_df

           BILL_DATE  MATERIAL SALES_DIST  SOLD_TO  SHIP_TO  PIEZAS
8511      2019-03-03      2641     100482  6001932  7003984       1
8512      2019-03-03     12916     100482  6001932  7003984       1
8513      2019-03-03      2464     100482  6001932  7003984       1
9478      2019-03-03     11074     100482  6001932  7003984       1
9479      2019-03-03     20306     100482  6001932  7003984       1
...              ...       ...        ...      ...      ...     ...
187373097 2021-03-31      2296     104862  6003121  7036861       1
187373098 2021-03-31      3590     104862  6003121  7036861       1
187373099 2021-03-31      8505     104862  6003121  7036861       1
187373100 2021-03-31     16951     104862  6003121  7036861       1
187373101 2021-03-31     19974     104862  6003121  7036861       1

[30605 rows x 6 columns]